### ISSUE TITLE
Assign RackGroups to a range of coordinates

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-app-floor-plan#10]
### Environment
* nautobot-floor-plan version:  0.9

### Proposed Functionality

It would be helpful to be able to define a "bounding box" for RackGroups within a Location and render that information on the FloorPlan SVG. For example, specifying that RackGroup "Aisle 1" covers the set of tiles falling between (1, 1) and (3, 20).

Possibly even provide an option to enforce this in some fashion, such as preventing you from associating a Rack to a tile that falls within a RackGroup that the Rack isn't a member of?

### Use Case

Data modeling, representation of reality.

**Comment by djhoward12** [comment]
I am currently working this issue.
