### ISSUE TITLE
Y Axis with large starting seed causes graphical bleeding

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot-app-floor-plan#116]
### Environment
* Python version:  3.11.9
* Nautobot version:  2.2.8
* nautobot-floor-plan version:  2.3.1b1

### Expected Behavior
Large Y Axis values (e.g., AAAA, 10000, etc.) looks correct on the side of the grid

### Observed Behavior
![Screenshot 2024-08-16 at 8 48 07 AM](https://github.com/user-attachments/assets/ca21adc0-e55b-422b-9f88-82139c045dbc)
![Screenshot 2024-08-16 at 8 48 40 AM](https://github.com/user-attachments/assets/0126947e-6228-44a8-aa04-cc743823d74d)

### Steps to Reproduce
1. Create a floor plan with large Y Axis seed

**Comment by djhoward12** [comment]
Made some modifications to move the Y_label_text to the left of the grid when the digits are more than two. Attached images of proposed change for review. 

**Numbers**
<img width="538" alt="2_numbers" src="https://github.com/user-attachments/assets/3b4d1463-2a58-4b17-9f14-4ad8d7b37757">
<img width="538" alt="3_numbers" src="https://github.com/user-attachments/assets/69115792-3be3-4138-8533-7c8527397ad6">
<img width="538" alt="4_numbers" src="https://github.com/user-attachments/assets/955dd6dc-ab27-44f7-b419-74bdf40128de">
<img width="538" alt="5_numbers" src="https://github.com/user-attachments/assets/efd80f8d-3463-4497-b009-02e1c4a1ad21">

**Letters**
<img width="538" alt="2_letters" src="https://github.com/user-attachments/assets/176f1319-98cc-4704-970f-08ea251cd547">
<img width="538" alt="3_letters" src="https://github.com/user-attachments/assets/5781fc3b-c369-4bc9-999b-0b9e81930437">
<img width="538" alt="4_letters" src="https://github.com/user-attachments/assets/e936f4c8-f6d1-48a3-a554-5a4d4401b466">

**Comment by joewesch** [comment]
I still feel like the 2 characters doesn't look good. It is over the line in certain situations and not centered. Can you change it so anything over 1 characters shifts it outside?
