### ISSUE TITLE
Association of Tenants/TenantGroups to a tile or group of tiles

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-app-floor-plan#12]
### Environment
* nautobot-floor-plan version:  0.9

### Proposed Functionality

Similar to #10, but allowing for the documentation and display of which Tenant(s) or TenantGroup(s) are assigned to a given group of tiles. Not clear at this time whether this would be a separate mapping between Tenant(Group) and FloorPlanTile, or whether this would just be an enhancement to the SVG render to display tenancy information derived from the Rack(Group).

### Use Case

More information easily visible to user.

**Comment by joewesch** [comment]
Completed and released in v2.2.0
