### ISSUE TITLE
Grid doesn't match what is displayed

### ISSUE THREAD

**Issue by collinsjas** [nautobot/nautobot-app-floor-plan#131]
### Environment
* Python version:  3.9
* Nautobot version:  2.3.8
* nautobot-floor-plan version:  2.4.0

I expect when I click on a tile to add a rack that it would be same Grid as what is displayed in the gui

When I click on the tile it is counting up when it should be going down.

1. Created a new floor
2. The X Axis Seed is BN
3. The X Axis step is -1 -- These displays correctly on the map. But doesn't match the clickable + icon
4. The Y is numbers and starts at 27
5. y Step is 1 - All of this is as expected

### Steps to Reproduce
1. If I click on any tile that is not in the first column (BN) it will be off.  It is ascending when it should be descending.
2. Click on BK 27 - opens the tile to add a rack at BQ 27

**Comment by joewesch** [comment]
Thanks for the report, @collinsjas. It looks like we'll need to adjust the form to calculate for negative steps - both on the initial value when clicking the `+` on the floor plan as well as the reverse.
