### ISSUE TITLE
Custom grid numbering in SVG render

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-app-floor-plan#8]
### Environment
* nautobot-floor-plan version:  0.9

### Proposed Functionality

Different users may have different grid numbering requirements when rendering as SVG, for example:

- alphabetical X axis (and what to do after A=26, "AA, AB, AC,..." or "A1, B1, C1, ..." or ...?) but numerical Y axis
- grid numbering to start at 0 or 5 instead of 1 (or some letter of the alphabet other than A)
- grid numbers to increment by 2 per tile instead of 1 per tile (or, eek, even half-steps per tile?)

### Use Case

Improved flexibility, support for more use cases.

**Comment by jvanderaa** [comment]
@itdependsnetworks this is pretty slick what you have there.
